version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - ./usr/app/node_modules
    
    env_file:
      - .env
    environment:
      NODE_ENV=production
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: example



volumes:
  dbdata:
